cse403-lemmeknow/lemmeknow

README.md
Add initial README file with description and goals.
- Add repository structure
=> Add initial README.

reports/20240124.md, reports/TEMPLATE.md
- Adds template weekly status report
- Adds initial weekly status report
N/A
N/A
- Fill out team report section
- Individually fill out individual sections
=> Add initial weekly status report and template.

README.md
Adds repository layout and a link to the living document to the README.
Markdown preview
N/A
N/A
=> Add layout, living document link to README.

backend/main.go
Allow the backend microservice to handle WebSocket events.
For now, it compiles.
Followup to #1 
- Test it within AWS (requires Terraform)
- Test it outside of AWS
=> Implement WebSocket event support.

reports/20240124.md
Added my weekly status report
N/A
N/A
N/A
=> added weekly status report

.github/CODEOWNERS, .github/workflows/build.yml, README.md, backend/database.go, backend/dbschema.go, backend/main.go
- Add GitHub action, which automatically tests the backend
- Update codeowners in preparation to change branch protection rules to rely on the GitHub action
- Format the backend code so the GitHub action format check succeeds
You are here
(I used `act` to locally ensure the action successfully runs)
Followup to #9
- Should also test frontend
=> Add GitHub action for automated status checking

.github/CODEOWNERS, reports/20240124.md
- Update weekly status report
- Test new `CODEOWNERS` file to make editing reports not require review
N/A
Followup to #6
N/A
=> Update weekly status report.

.github/workflows/backend.yml, README.md
Only run backend automated status check if backend code changed.
You are here.
N/A
N/A
=> Only test backend if its files changed.

reports/20240124.md
=> Write team weekly status report.

backend/api.go, backend/main.go, backend/session.go
- Modularize backend API.
- Add a draft session API.
CI
Followup to #1
N/A
=> Modularize API, add draft session API.

backend/database.go, backend/dbschema.go, reports/20240124.md
=> Added weekly status update & revise database code format

reports/20240124.md
anyone please approve my weekly report LOL
N/A
N/A
N/A
=> add Zohar's report

reports/20240124.md
- Add weekly report entry for Mohamad, based on
- Living document
- Discord messages
N/A
N/A
N/A
=> Add weekly report on behalf of Mohamad.

.github/workflows/terraform.yml, README.md, backend/.gitignore, terraform/.gitignore, terraform/Makefile, terraform/README.md, terraform/provider.tf, terraform/variable.tf
- Add a directory for writing a Terraform configuration
- Use a remote state provider
- Add some quality of life scripts
- Add a CI status checker to ensure it stays formatted
N/A
- Need to write the actual infrastructure configuration
=> Setup a directory for Terraform

reports/20240131.md
=> Add second weekly report.

backend/api.go, backend/main.go, backend/main_test.go, backend/session.go
- Implement session API (create a user, set a cookie)
- Add support for EventBridge events
New test
N/A
Need more sensitive test that checks cookies
=> Implement session API.

terraform/README.md
=> Fix README typo.

backend/README.md, backend/api.go, backend/database.go, backend/go.mod, backend/go.sum, backend/group.go, backend/main.go, backend/main_test.go, backend/user.go
- Start implementing user and group API's
- Switch to `gorilla/mux` HTTP router for path parameters
- Had to remove one of the tests for now
N/A
- Adding the remainder of the API interfaces
=> Start implementing user and group API's.

.github/workflows/backend.yml, backend/README.md, backend/group.go
- Design most remaining API's in backend README.md
N/A
N/A
N/A
=> Design most other API's.

backend/README.md
- Add new API's
- Change existing API's
N/A
N/A
N/A
=> Update API docs.

backend/README.md
- Add new API's
- Change existing API's
- Importantly, moving availability from user to group.
N/A
N/A
N/A
=> More API redesigns (attempt 2).

reports/20240131.md
=> Update second report.

backend/README.md, backend/api.go, backend/dbschema.go, backend/go.mod, backend/go.sum, backend/group.go, backend/group_chat.go, backend/main.go, backend/main_test.go, backend/user.go, frontend/README.md, frontend/src/lib/model.js, frontend/src/routes/+page.svelte
- Integrate backend and frontend on localhost
- Backend acts as a reverse proxy to the local frontend origin server
Manual only for now.
N/A
Automated testing.
=> Initial integration of backend and frontend.

backend/README.md, frontend/vite.config.js
Attempt to fix automatic refreshing.
N/A
N/A
N/A
=> Random refresh workaround.

frontend/package-lock.json, frontend/src/routes/+page.svelte, frontend/src/routes/devteam.svelte, frontend/src/routes/features.svelte, frontend/src/routes/privacy.svelte
Add package lock json back
N/A
N/A
N/A
=> add package-lock-json

terraform/.terraform.lock.hcl, terraform/acm.tf, terraform/apigateway_rest.tf, terraform/apigateway_ws.tf, terraform/cloudfront.tf, terraform/dynamodb.tf, terraform/eventbridge.tf, terraform/iam.tf, terraform/lambda.tf, terraform/route53.tf, terraform/s3.tf
- Create Lambda terraform configuration
- Create IAM configuration
- Create API Gateway REST configuration
- Add TODO comments for other essential configurations
N/A
N/A
N/A
=> Get started on Terraform configuration.

reports/20240131.md
Added Weekly Report
N/A
N/A
N/A
=> Added Weekly Report

frontend/src/routes/dashboard/+page.svelte, reports/20240131.md
Create chatbot and add weekly report
N/A
N/A
N/A
=> Chatbox implement

.github/workflows/frontend.yml, README.md
adding frontend yml for automated testing
N/A
N/A
N/A
=> added frontend yml for automatic testing

.github/workflows/frontend.yml, README.md
node js version upgrade
N/A
N/A
N/A
=> upgrade node js version

.github/workflows/frontend.yml, README.md, frontend/src/routes/+page.svelte, frontend/src/routes/dashboard/+page.svelte
get rid of type check in yml
N/A
N/A
N/A
=> get rid of type check in yml

backend/database.go, backend/database_test.go, backend/dbschema.go
=> Revise database API layer + added unit test (rough draft)

backend/README.md, backend/database.go, backend/dbschema.go, backend/group_chat.go, backend/group_poll.go, backend/main.go
- Implement more API's
- Chat
- Poll
- Fix some schema issues
- Fix an API design naming issue
- Make in-memory database threadsafe
CI
N/A
- The other API's
- Implementing new DB methods
=> Implement chat and poll API's.

reports/20240207.md
=> Add third report.

backend/database.go, backend/group.go, backend/group_chat.go, backend/main.go, backend/main_test.go, backend/user.go
Introduce backend Rest API tests.
You are here.
N/A
N/A
=> Add more backend tests.

README.md
=> Add Terraform CI badge to README.

.github/workflows/backend.yml, backend/database.go, backend/database_test.go, backend/dbschema.go, backend/go.mod, backend/go.sum
- Install DynamoDB Local in CI
You are here.
N/A
N/A
=> Allow DynamoDB unit tests to run in CI

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml, CONTRIBUTING.md, LICENSE, README.md, backend/README.md, terraform/README.md
- Contribution guide
- Issue templates
- Readme's
N/A
N/A
N/A
=> Finish developer guides.

backend/database.go, backend/dbschema.go, backend/group.go, backend/group_activity.go, backend/group_availability.go, backend/group_poll.go
- Implement addition aspects of group, activity, and availability API's
- Simplify database update to just one transactional function per table
N/A
N/A
N/A
=> Refine backend API's.

backend/README.md, backend/database.go, backend/group.go, backend/group_availability.go, backend/group_chat.go, backend/group_poll.go, backend/main_test.go
- Add backend API integration tests
- Fix backend bugs/typos
You are here.
N/A
N/A
=> Add tests for backend API's, fix discovered bugs.

backend/README.md, backend/group.go, backend/group_activity.go, backend/group_availability.go, backend/group_chat.go, backend/group_poll.go, backend/main_test.go
- Test subtle backend API's for removing availabilities and activites
- Improve API spec and conformance
You are here.
N/A
N/A
=> Test subtle backend API's.

backend/api.go, backend/group.go, backend/notification.go
- Implement backend websocket notifications
- Use them on just one API
N/A
N/A
Notifications for other API's, and making sure it works end-to-end.
=> Implement backend notifications.

backend/database_test.go
=> revise database_test

backend/database.go, backend/database_test.go
Fixes the backend test of the CI build.
N/A
Followup to #83 
N/A
=> Fix the CI build.

reports/20240207.md
=> Update third report.

backend/database.go, backend/dbschema.go
=> implemented update user and create message API

terraform/acm.tf, terraform/cloudfront.tf, terraform/dynamodb.tf, terraform/lambda.tf, terraform/s3.tf
Prepare Terraform configurations for provisioning infrastructure by improving consistency (most importantly, between the configuration and our requirements).
N/A
N/A
N/A
=> Improve Terraform configurations.

reports/20240207.md
=> Update 3rd report.

backend/README.md, backend/database.go, backend/database_test.go, backend/dbschema.go, backend/group.go, backend/group_task.go, backend/main_test.go, reports/20240207.md
- Design Task API
- Implement Task API
- Add backend integration tests for Task API
N/A
N/A
=> Design, implement, and test tasks API.

reports/20240207.md
Brooklyn Weekly Status Report 02/07
N/A
N/A
N/A
=> Weekly Status Report 02/07

reports/20240207.md
=> daven report for 7 feb

reports/20240207.md
=> Finalize 3rd report.

reports/20240214.md
=> Create 4th report from template.

backend/api.go, backend/group.go, backend/group_activity.go, backend/group_availability.go, backend/group_chat.go, backend/group_poll.go, backend/group_task.go, backend/main_test.go, backend/notification.go, backend/user.go, terraform/lambda.tf
- Backend sends notifications for all group updates
- Backend sends notifications for all member updates
- Backend sends notifications for all chat updates
Make sure at least one notification of each type is sent.
N/A
N/A
=> Backend sends notifications for all events

README.md, backend/Makefile, backend/README.md, frontend/Makefile, frontend/README.md, reports/20240214.md, terraform/README.md
=> Overhaul developer guides.

.github/workflows/backend.yml, .github/workflows/frontend.yml, .github/workflows/terraform.yml, CONTRIBUTING.md, README.md, backend/Makefile, backend/database.go, frontend/.prettierignore
- Contributing guide warning about fmt/lint
- Add linting to backend
- Don't run backend test CI until backend build CI passes
N/A
N/A
N/A
=> Further improvements to developer guides/CI.

reports/20240214.md
=> Update 4th report.

backend/README.md
Make documentation more explicit and free of typos.
N/A
N/A
N/A
=> Improve backend API documentation.

frontend/src/lib/model.js, frontend/src/lib/stores.js, frontend/src/routes/+page.svelte, frontend/src/routes/dashboard/+page.svelte, frontend/vite.config.js
Supporting Integration for creating group, creating task, and creating availabilities
N/A
N/A
N/A
=> Supporting Integration for creating group, creating task, and creating availabilities

backend/api.go, backend/database.go, backend/dbschema.go, backend/main.go, terraform/dynamodb.tf, terraform/lambda.tf
Troubleshoot issues with websockets in AWS.
- Knowing which user they correspond to
- IAM permissions to send/receive
- Database transaction issues
Manual
N/A
N/A
=> WebSockets work in AWS.

reports/20240214.md
=> Update 4th report (part 2).

reports/20240214.md
=> add daven's partial report

reports/20240214.md
=> daven status for 14Feb

.github/CODEOWNERS, backend/README.md, backend/database.go, backend/dbschema.go, backend/group.go, backend/group_activity.go, backend/group_availability.go, backend/group_chat.go, backend/group_poll.go, backend/group_task.go, backend/main.go, backend/main_test.go, backend/notification.go, backend/push.go, backend/util.go, backend/util_test.go, terraform/dynamodb.tf
- Improves quality of backend test suite
- Ensures tasks, availabilities, activities, and polls get deleted when requested
- More assertions about added availabilities and activities
- Adds API that, while testing, I noticed was missing (editing/confirming activity)
- Removes redundant code (push notification related)
- Creates a new file for utility functions
- Adds a few input validation checks (string length, utf8 validity, date, time)
- Adds a few comments
- Updates CODEOWNERS, including with respect to files in backend
You are here.
N/A
N/A
=> Test and improve backend.

CONTRIBUTING.md, README.md, frontend/Makefile, reports/20240221.md
- Title
- <sub>Add 5th report</sub>
N/A
N/A
N/A
=> Enhance testing instructions in dev guide.

backend/api.go, backend/database.go, backend/main.go
- Frontend can successfully send chat via REST and receive chat via WebSocket
N/A
N/A
N/A
=> Frontend and backend integration (chat)

reports/20240221.md
=> Update 5th report.

backend/database.go
=> added new database APIs

backend/README.md, backend/group_chat.go, backend/notification.go, backend/push.go
=> Send push notification for chat.

backend/database.go
Title
Successfully created VAPID keys, which uses a variable.
N/A
N/A
=> Fix database bugs concerning the variable table.

reports/20240221.md
=> weekly status report 2/21

frontend/src/routes/dashboard/[groupId]/+page.svelte
=> fix copy invite link button

reports/20240221.md
=> daven weekly report 21 Feb

reports/20240221.md
=> Update Mohamad 20240221.md

backend/api.go, backend/group.go, backend/group_activity.go, backend/group_availability.go, backend/group_poll.go, backend/group_task.go, backend/util.go
Limit total amount of data per user/group.
TBD
N/A
N/A
=> Add limit on data per user/group.

backend/README.md, backend/main_test.go, backend/user.go, backend/util.go
Add API that will be useful for implementing the remainder of the frontend.
Added corresponding test.
N/A
N/A
=> Add API to get specific user.

frontend/src/routes/dashboard/[groupId]/+page.svelte
Tasks and availability populates screen when link is reloaded
N/A
N/A
N/A
=> Tasks and availability populates screen when link is reloaded

reports/20240228.md
=> Create 6th report.

reports/20240228.md
=> daven 28 feb status

reports/20240228.md
=> add report - zohar

backend/group_activity.go, backend/group_poll.go, backend/group_task.go, frontend/src/lib/model.js, frontend/src/routes/dashboard/[groupId]/+page.svelte
Connected Self Assigning and completion status for tasks to backend
N/A
N/A
N/A
=> Connected Self Assigning and completion status for tasks to backend

reports/20240228.md
=> Update 6th report.

backend/api.go, backend/go.mod, backend/go.sum, backend/main.go, backend/main_test.go, backend/scheduler.go, terraform/lambda.tf, terraform/scheduler.tf
=> Add date-aware scheduler to backend for reminders.

backend/group.go, backend/user.go, frontend/src/routes/dashboard/[groupId]/+page.svelte, frontend/vite.config.js
=> Calculating the overlapping availabilities + only showing availability based on userId

backend/database.go, frontend/src/lib/model.js, frontend/src/routes/dashboard/[groupId]/+page.svelte
- Makes availability and task related code (mostly in the frontend) more correct, concise, and idiomatic.
- Most important change is rendering state from the backend instead of intermediate stores.
- Directly create availabilities instead of a separate save button
Manually tested availabilities and tasks with two different browsers.
N/A
N/A
=> Fix availabilities and tasks.

frontend/src/lib/model.js, frontend/src/routes/dashboard/[groupId]/+page.svelte
=> Task Assignee using name instead of userid

backend/database.go, backend/go.mod, backend/go.sum, frontend/src/lib/model.js, frontend/src/routes/dashboard/[groupId]/+page.svelte
=> Merge main into Chat Poll for zohar

frontend/src/lib/model.js, frontend/src/routes/dashboard/[groupId]/+page.svelte, frontend/src/routes/devteam/+page.svelte, frontend/src/routes/features/+page.svelte, frontend/src/routes/privacy/+page.svelte
=> Member Icon now shows member status

backend/README.md, backend/group.go, backend/user.go
Fixes backend issues we recently noticed when implementing frontend.
CI
N/A
N/A
=> Better docs, protocol, privacy.

README.md
=> Fix #153 - add features/use-case info to readme.

frontend/src/routes/features/+page.svelte
=> Add use cases/features into features svelte

frontend/src/routes/features/+page.svelte, frontend/src/routes/privacy/+page.svelte
=> Making the Privacy Policy Page Prettier

frontend/src/routes/dashboard/[groupId]/+page.svelte
=> fix - each user can only update their own status

frontend/src/routes/dashboard/[groupId]/Chat.svelte
TBD
Do some manual UI tests
N/A
N/A
=> add user name for chat

frontend/src/lib/model.js, frontend/src/routes/dashboard/[groupId]/+page.svelte
=> display messages on active

backend/database.go, frontend/src/lib/model.js
Title
Manual (new messages and refreshing page)
N/A
N/A
=> Display chat in chronological order.

frontend/src/routes/dashboard/[groupId]/+page.svelte, frontend/src/routes/dashboard/[groupId]/Chat.svelte
Display active poll when a new user just join. Poll disappear on chat box if click on poll button again
N/A
N/A
N/A
=> display poll and not display  poll

frontend/src/routes/dashboard/[groupId]/+page.svelte, frontend/src/routes/dashboard/[groupId]/Chat.svelte, frontend/src/routes/dashboard/[groupId]/PollCreationModal.svelte
=> add chat style

reports/20240306.md
=> Create last report.

README.md, frontend/src/routes/features/+page.svelte
=> Mention user manual in README.md.

frontend/src/lib/model.js
Continue to fetch more than 5 messages
TBD
N/A
N/A
N/A
=> continue to fetch messages

backend/push.go, frontend/src/app.html, frontend/static/serviceWorker.js, frontend/static/subscribe.js, reports/20240306.md
=> Integrate WebPush notifications for chat.

reports/20240306.md
=> add report

reports/20240221.md, reports/20240306.md
=> Zohar report 3 6

frontend/src/routes/dashboard/[groupId]/+page.svelte, reports/20240221.md, reports/20240306.md
=> Zohar add group name
